guid: FLIR-19444692
camera_info_url: package://camera_aravis/config/auv4/front_cam_calib.yaml
camera_name: auv4/front_cam

Acquire: True
ExposureAuto: Continuous
GainAuto: Continuous
ExposureTimeAbs: 2000.0
Gain: 1.0

BalanceWhiteAuto: Continuous

AcquisitionMode: Continuous
AcquisitionFrameRate: 20.0
AcquisitionFrameRateEnable: True

TriggerMode: Off

BinningHorizontal: 2
BinningVertical: 2

frame_id: auv4/front_cam_optical

PixelFormat: BayerRG8
mtu: 9000
